### PR TITLE
Switch config from JSON to TOML

### PR DESCRIPTION
**Pull request by callahad**
In support of #32.

Currently based on #40; waiting for that to get merged before opening this up as a formal PR, but feel free to comment on my five commits at the end of this branch.

### CODE REVIEW

**Comment by callahad** [comment]
This should be merge-able. r? @djc or @stephank

**Comment by djc** [comment]
Should we get rid of `docopt` at this point? It doesn't seem to provide us with much value now. 

Why not put ip and port in a single addr config value? 

If the main advantage for TOML is that we can put comments in there, let's actually do so and get rid of the duplication between test file and README contents?

**Comment by callahad** [comment]
> Should we get rid of docopt at this point? It doesn't seem to provide us with much value now. 

Probably.

> Why not put ip and port in a single addr config value? 

Cleaner semantics / granularity with regard to env vars. E.g., Heroku and other common PaaS's just provide `PORT` as an env var.

> If the main advantage for TOML is that we can put comments in there, let's actually do so and get rid of the duplication between test file and README contents?

On the way! :)

**Comment by callahad** [comment]
Hitting the green button, given the approvals above

**Comment by callahad** [comment]
Upon reflection, I still think docopt is useful, even if all it does is provide meaningful responses to `--help` and `--version`. Sure, we could manually do that, but docopt is already there, and it works.

**Pull request merged**
