### PR TITLE
Improve email code readability.

### PR DESCRIPTION
**Pull request by stephank**
This puts the code on its own line, makes it monospace and larger.

screen shot 2016-11-17 at 11 40 34

### CODE REVIEW

**Comment by callahad** [comment]
LGTM! Thanks!

**Comment by callahad** [comment]
Huh, nope, the "update branch" button doesn't exactly do what I wanted it to do. Thanks GitHub.

@stephank: Would you mind rebasing and force-pushing to this branch, instead?

**Comment by stephank** [comment]
@callahad Done. In hindsight, think this could've worked with update + squash & merge? Anyway, either of us can merge on the green light.

**Comment by callahad** [comment]
Good point re: squash and merge :)

**Pull request merged**
