### PR TITLE
Fix/documentation

### PR DESCRIPTION
**Pull request by skorokithakis**
I've made a few fixes to the documentation, to make it more readable.

Main questions I have now:

* What's `keytext`?
* Is redis mandatory? If yes, aww :( If no, why does the readme say the redis address must be set?

### CODE REVIEW

**Comment by skorokithakis** [comment]
@stephank, @djc, can either of you clarify the above questions? Ideally, I'd like to get this merged before launch to help first-time users.

**Comment by stephank** [comment]
@skorokithakis Where keyfiles contains filenames, is an alternative to specify PEM contents directly.

Redis is mandatory, yes.

Also, for the changes to the README tables, please align them in the rst source too. :)

**Comment by skorokithakis** [comment]
Ah, oops, good catch. So we either need to set `keyfiles` OR `keytext`?

**Comment by skorokithakis** [comment]
Ah, never mind, the readme does say *or*. Thanks.

**Comment by stephank** [comment]
Good question! It looks like, right now, you can specify both too. `keyfiles` can be keys, and `keytext` can just be one right now. If you specify both, `keytext` will be treated as 'after' the `keyfiles`.

Whichever key is last in the internal list is used as our signing key, so if you specify a `keytext`, it'll always be that one.

**Pull request merged**
