### PR TITLE
Workaround Clippy failures on current Nightly

### PR DESCRIPTION
**Pull request by callahad**

### CODE REVIEW

**Comment by callahad** [comment]
Okay, we've got options:

- Disable Clippy on nightly for now
- Allow builds on nightly to soft-fail without blocking PRs
- Pin our rustc to nightly-2016-11-24 and clippy to 0.0.103 for now
- Any combination of the above

**Comment by callahad** [comment]
The first two options don't get us any Clippy information at all, but we do want to know when the third option stops being necessary. So let's:

1. Allow builds on `nightly` to fail
2. Add a temporary `nightly-2016-11-24` build that is not allowed to fail

**Comment by stephank** [comment]
Ref to clippy bug: https://github.com/Manishearth/rust-clippy/issues/1371

I like that last option. :)

**Pull request merged**
