### PR TITLE
return verified_email as a bool (true) per oidc recommendations

### LINKED ISSUE #173: claim `email_verified` should be a boolean
See here: https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims

### PR DESCRIPTION
**Pull request by colemickens**
Fixes #173.

### CODE REVIEW

**Comment by stephank** [comment]
We definitely want this, but it's another question of 'what will it break'. :/

There's currently not really an upgrade plan for the protocol, though technically we're not stable yet. We don't even announce these changes yet.

**Comment by colemickens** [comment]
Understood. I'd be happy to move it behind a flag? Same with my other open PR? Let me know what you think.

**Comment by onli** [comment]
I'm for merging it. We did not give stability guarantees yet, and the clients we know about we control and can change before the merge. Though the ruby client for example would not be affected by this. And we have to clear up the emails in the token (i.e. for normalization) anyway.

**Comment by colemickens** [comment]
Would it help if I hosted an instance of Portier with this and the login_hint patch applied? And then I guess we could validate clients (do they each have tests, or example harness applications?)

**Comment by stephank** [comment]
Well, all of the clients in the Portier organisation don't even use `email_verified`. It's more about what's out there we don't know of and can't test.

But you're right, @onli, though maybe we should send a short announcement to the mailinglist before deploying.

**Comment by onli** [comment]
Thanks you for addressing this. I merged it, we already waited too long.

**Pull request merged**
